### ISSUE TITLE
My personal review

### ISSUE THREAD

**Issue by diegosaul402** [kerbero1994/Assigment-MagmaHackers-First#3]
Hi Eduardo, I have a few things to say, I hope helps you to improve your page.
Your profile image needs to be resized, you can resize your source img or give an fixed size in code. It is not bad, is just covers your menu bar and your contact info.
About your git record, you need to put more descriptive titles to your commits, must reflects what changes or additions has in it.
It is admirable you write your page without any frameworks help. Myself couldn't do it like you do.
Your code have a few identation errors, no big deal.
Anyways, good job.

**Comment by kerbero1994** [comment]
Hello, good night, thanks for your feedback, the details in the image do not happen in Firefox, thanks to your comment I realize the error present in other browsers, and about git record, I uploaded the project a couple of times due to some errors when creating the repo, and forget to put the descriptions thank you for reminding me.
